<?php

/**
 * @file
 * Alters the login destination of users.
 */

/**
 * Implements hook_user_login().
 */
function gsb_login_destination_user_login(&$edit, $account) {
  if (user_access('access workbench')) {
    $GLOBALS['destination'] = "admin/workbench";
  }
  if (field_info_instance('node', 'field_sunetid', 'faculty')) {
    $query = new EntityFieldQuery('node');
    $results = $query
      ->entityCondition('bundle', 'faculty')
      ->fieldCondition('field_sunetid', 'value', $account->name)
      ->execute();
    if (!empty($results['node'])) {
      $nid = key($results['node']);
      $GLOBALS['destination'] = "node/$nid/edit";
    }
  }
}
